### PR TITLE
Composer Updates

### PR DESCRIPTION
**Pull request by 0aveRyan**
### Optimize Composer autoloader

The Composer autoloader [should be optimized for production environments](https://getcomposer.org/doc/articles/autoloader-optimization.md). The performance benefit to individual requests is minimal, but for the farm in-aggregate should compound to more significant savings over time.

### CODE REVIEW

**Comment by 0aveRyan** [comment]
TODO:
* Test on bluerock and legacy
* Relocate `.staging` script
* Remove jetpack onboarding now that code is included using composer.

**Comment by wpscholar** [comment]
@0aveRyan I'm not a big fan of changing from `vendor` to `lib`. 

Here's my reasoning:

1. We have other things already in a `lib` directory (albeit things we will be removing)
2. I think straying from the convention of where Composer stores dependencies could introduce unnecessary confusion. The fact that dependencies are "internal" is irrelevant. The `vendor` directory is generally viewed as a black box where any code that isn't part of the current repos lives.
4. I don't think saving 3 characters in our URLs is that big of a deal. ;)

**Comment by 0aveRyan** [comment]
@wpscholar circling back, while I get pros and cons.. still prefer `/lib`. Not something I feel _super_ strongly about 😇  But the optimize autoloader is something we should try to get shipped in next release

**Comment by earnjam** [comment]
It wouldn't bother me too much either way, but I tend to agree with @wpscholar here about keeping `vendor`. 

I'm on board with the autoload optimization though.

**Pull request merged**
