### PR TITLE
Improve internationalization within the plugin

### PR DESCRIPTION
**Pull request by desrosj**
Improves the internationalization of the plugin by ensuring all strings are correctly wrapped with gettext.

### CODE REVIEW

**Comment by wpscholar** [comment]
@desrosj Here is the Pig Latin plugin: https://wordpress.org/plugins/piglatin/

If you activate it and browse the plugin, you'll see that there are definitely a few strings in the plugin that aren't being translated.

**Comment by wpscholar** [comment]
@desrosj Also, not sure if we should load languages on `init` or not? (See: https://developer.wordpress.org/reference/functions/load_plugin_textdomain/#comment-1568)

**Comment by desrosj** [comment]
@wpscholar Ah, the plugin handbook internationalization documentation has `plugins_loaded`. I'm assuming the `init` comment is correct. I'm going to try and confirm with someone from polyglots so we can do it right, and we can update the documentation too.

**Comment by desrosj** [comment]
@0aveRyan Alright, try now!

**Pull request merged**
