### PR TITLE
Coming Soon notification updates

### PR DESCRIPTION
**Pull request by ianbelanger79**
Changes remove the flag from the Coming Soon Active panel on the Bluehost admin homepage and change the action color in the admin menu item and Coming Soon Active panel from red #ce0000 to orange #F89C24

coming-soon-no-flag

### CODE REVIEW

**Comment by ianbelanger79** [comment]
> So with that particular orange, the contrast of the white text on it is only 2.15.

> WEBAim guidelines recommend AA as a minimum, which would require a ratio of 4.5. If we make the text color black, then it would be 6.92.

I agree with you @earnjam. This was something I actually brought up when we talked about it in our meeting. I will ping Jenny and Mike with a screenshot using black text.

**Comment by ianbelanger79** [comment]
> Other question I had, was the left border of the notification banner on the plugin dashboard page supposed to be orange also? I think it was in the screenshot you posted in Hipchat yesterday, but it's currently red on this PR.

It was changed in the stylesheet and you can see that change here: https://github.com/mojoness/mojo-marketplace-wp-plugin/blob/5dfcedba917f60de236e459545ad5a1993d64fc8/assets/css/bluerock.css#L319-L322 The stylesheet may be cached in your browser, because it is working for me.

**Comment by earnjam** [comment]
@ianbelanger79 The CSS for `.panel-warning` uses `#F89C24`, but the HTML is using the `.panel-error` class, which is still set to `#dc3232`

**Comment by ianbelanger79** [comment]
> @ianbelanger79 The CSS for `.panel-warning` uses `#F89C24`, but the HTML is using the `.panel-error` class, which is still set to `#dc3232`

@earnjam Ok, I do see that now. I thought I already changed that class. I will make the change. Guess it must be cached on my browser

**Pull request merged**
